openapi: 3.0.1
info:
  title: Introdução
  description: |
    Otimize a gestão financeira da sua operação com eficiência e segurança.
    Organize livros razão, monitore transações e saldos em tempo real, e
    consolide dados com precisão. Automatize processos com Smart Transactions,
    garantindo controle total, rastreabilidade e integridade das transações financeiras.


    Saiba mais sobre o Ledger Kernel Engine [aqui](https://hub.guardia.finance/docs/modules<https://{tenant_id}.guardia.finance/lke).

    ## Comunidade

    Faça parte da nossa comunidade no WhatsApp.


    [![WhatsApp](https://img.shields.io/badge/WhatsApp-25D366?style=for-the-badge&logo=whatsapp&logoColor=white)](https://chat.whatsapp.com/BcngCJx3ytzHy9AeZWzRg2)

  version: 1.0.0
  contact:
    name: Guardia
    url: https://www.guardia.finance/#contact-us
    email: contato@guardia.finance
  license:
    name: Apache 2.0
    url: https://github.com/guardiafinance<https://{tenant_id}.guardia.finance/lke/blob/main/LICENSE
  x-logo:
    url: "/img/banner-lke.svg"
    altText: Ledger Kernel Engine Banner
  x-dark-logo:
    url: "/img/banner-lke.svg"
    altText: "Ledger Kernel Engine Banner"
tags:
  - name: Ledger
    description: |
      Gerencie os livros razão da sua empresa. Crie, atualize e exclua ledgers,
      além de consultar informações detalhadas sobre cada um.
  - name: Chapter
    description: |
      Organize os livros razão em capítulos para facilitar a gestão e análise.
      Crie, atualize e exclua capítulos, além de consultar informações detalhadas sobre cada um.
  - name: Asset
    description: |
      Gerencie os ativos da sua empresa. Crie, atualize e exclua ativos,
      além de consultar informações detalhadas sobre cada um.
  - name: Transaction
    description: |
      Registre transações financeiras relacionadas a um livro razão ou capítulo.

paths:
  /v1/ledgers:
    get:
      summary: Lista todos os ledgers
      deprecated: false
      description: 'Obténha uma lista de ledgers disponíveis para a organização filtrando por metadata ou incluindo itens descartados.'
      operationId: list_ledgers
      tags:
        - Ledger
      parameters:
        - $ref: './components.openapi.yaml#/components/parameters/EntityIds'
        - $ref: './components.openapi.yaml#/components/parameters/ExternalEntityIds'
        - $ref: './components.openapi.yaml#/components/parameters/MetadataFilter'
        - $ref: './components.openapi.yaml#/components/parameters/IncludeDiscarded'
        - $ref: './components.openapi.yaml#/components/parameters/PageSize'
        - $ref: './components.openapi.yaml#/components/parameters/PageToken'
        - $ref: './components.openapi.yaml#/components/parameters/OrderBy'
        - $ref: './components.openapi.yaml#/components/parameters/Sort'
        - $ref: './components.openapi.yaml#/components/parameters/Accept'
        - $ref: './components.openapi.yaml#/components/parameters/AcceptLanguage'
        - $ref: './components.openapi.yaml#/components/parameters/ContentType'
        - $ref: './components.openapi.yaml#/components/parameters/CorrelationId'
      responses:
        '200':
          description: Lista de ledgers
          content:
            application/vnd.guardia.v1+json:
              schema:
                type: object
                properties:
                  data:
                    $ref: './components.openapi.yaml#/components/schemas/ListOfLedgers'
                  pagination:
                    $ref: './components.openapi.yaml#/components/schemas/Pagination'
          headers:
            Cache-Control:
              $ref: './components.openapi.yaml#/components/headers/Cache-Control'
            Content-Language:
              $ref: './components.openapi.yaml#/components/headers/Content-Language'
            Content-Length:
              $ref: './components.openapi.yaml#/components/headers/Content-Length'
            Content-Type:
              $ref: './components.openapi.yaml#/components/headers/Content-Type'
            Link:
              $ref: './components.openapi.yaml#/components/headers/Link'
            Strict-Transport-Security:
              $ref: './components.openapi.yaml#/components/headers/Strict-Transport-Security'
            X-Grd-Correlation-Id:
              $ref: './components.openapi.yaml#/components/headers/X-Grd-Correlation-Id'
            X-Grd-Trace-Id:
              $ref: './components.openapi.yaml#/components/headers/X-Grd-Trace-Id'
            X-RateLimit-Limit:
              $ref: './components.openapi.yaml#/components/headers/X-RateLimit-Limit'
            X-RateLimit-Remaining:
              $ref: './components.openapi.yaml#/components/headers/X-RateLimit-Remaining'
            X-RateLimit-Reset:
              $ref: './components.openapi.yaml#/components/headers/X-RateLimit-Reset'
        '400':
          $ref: './components.openapi.yaml#/components/responses/Error400'
        '401':
          $ref: './components.openapi.yaml#/components/responses/Error401'
        '403':
          $ref: './components.openapi.yaml#/components/responses/Error403'
        '404':
          $ref: './components.openapi.yaml#/components/responses/Error404'
        '409':
          $ref: './components.openapi.yaml#/components/responses/Error409'
        '422':
          $ref: './components.openapi.yaml#/components/responses/Error422'
        '429':
          $ref: './components.openapi.yaml#/components/responses/Error429'
        '500':
          $ref: './components.openapi.yaml#/components/responses/Error500'
      security: []
      x-apidog-folder: Ledger
      x-apidog-status: developing
      x-apidog-maintainer: Fernando Seguim
      x-run-in-apidog: https://app.apidog.com/web/project/719079/apis/api-11718079-run
    post:
      summary: Cria um novo ledger
      description: Cria um novo ledger com os dados fornecidos.
      operationId: create_ledger
      tags:
        - Ledger
      parameters:
        - $ref: './components.openapi.yaml#/components/parameters/IdempotencyKey'
        - $ref: './components.openapi.yaml#/components/parameters/Accept'
        - $ref: './components.openapi.yaml#/components/parameters/AcceptLanguage'
        - $ref: './components.openapi.yaml#/components/parameters/ContentType'
        - $ref: './components.openapi.yaml#/components/parameters/CorrelationId'
      requestBody:
        required: true
        content:
          application/vnd.guardia.v1+json:
            schema:
              $ref: './components.openapi.yaml#/components/schemas/LedgerCreateRequest'
      responses:
        '201':
          description: Ledger criado com sucesso.
          headers:
            Content-Type:
              $ref: './components.openapi.yaml#/components/headers/Content-Type'
            Content-Length:
              $ref: './components.openapi.yaml#/components/headers/Content-Length'
            Content-Language:
              $ref: './components.openapi.yaml#/components/headers/Content-Language'
            Cache-Control:
              $ref: './components.openapi.yaml#/components/headers/Cache-Control'
            Idempotency-Key:
              $ref: './components.openapi.yaml#/components/headers/Idempotency-Key'
            Content-Digest:
              $ref: './components.openapi.yaml#/components/headers/Content-Digest'
            Last-Modified:
              $ref: './components.openapi.yaml#/components/headers/Last-Modified'
            X-Grd-Correlation-Id:
              $ref: './components.openapi.yaml#/components/headers/X-Grd-Correlation-Id'
            X-Grd-Trace-Id:
              $ref: './components.openapi.yaml#/components/headers/X-Grd-Trace-Id'
            X-RateLimit-Limit:
              $ref: './components.openapi.yaml#/components/headers/X-RateLimit-Limit'
            X-RateLimit-Remaining:
              $ref: './components.openapi.yaml#/components/headers/X-RateLimit-Remaining'
            X-RateLimit-Reset:
              $ref: './components.openapi.yaml#/components/headers/X-RateLimit-Reset'
          content:
            application/vnd.guardia.v1+json:
              schema:
                type: object
                properties:
                  data:
                    $ref: './components.openapi.yaml#/components/schemas/Ledger'
        '400':
          $ref: './components.openapi.yaml#/components/responses/Error400'
        '401':
          $ref: './components.openapi.yaml#/components/responses/Error401'
        '403':
          $ref: './components.openapi.yaml#/components/responses/Error403'
        '404':
          $ref: './components.openapi.yaml#/components/responses/Error404'
        '409':
          $ref: './components.openapi.yaml#/components/responses/Error409'
        '422':
          $ref: './components.openapi.yaml#/components/responses/Error422'
        '429':
          $ref: './components.openapi.yaml#/components/responses/Error429'
        '500':
          $ref: './components.openapi.yaml#/components/responses/Error500'
      security:
        - BearerAuth: []
  /v1/ledgers/{entity_id}:
    get:
      summary: Obtém um ledger específico
      deprecated: false
      description: ''
      operationId: get_ledger
      tags:
        - Ledger
      parameters:
        - $ref: './components.openapi.yaml#/components/parameters/EntityId'
        - $ref: './components.openapi.yaml#/components/parameters/Accept'
        - $ref: './components.openapi.yaml#/components/parameters/AcceptLanguage'
        - $ref: './components.openapi.yaml#/components/parameters/ContentType'
        - $ref: './components.openapi.yaml#/components/parameters/CorrelationId'
      responses:
        '200':
          description: Dados do ledger.
          content:
            application/vnd.guardia.v1+json:
              schema:
                type: object
                properties:
                  data:
                    $ref: './components.openapi.yaml#/components/schemas/Ledger'
          headers:
            Cache-Control:
              $ref: './components.openapi.yaml#/components/headers/Cache-Control'
            Content-Language:
              $ref: './components.openapi.yaml#/components/headers/Content-Language'
            Content-Length:
              $ref: './components.openapi.yaml#/components/headers/Content-Length'
            Content-Type:
              $ref: './components.openapi.yaml#/components/headers/Content-Type'
            Strict-Transport-Security:
              $ref: './components.openapi.yaml#/components/headers/Strict-Transport-Security'
            X-Grd-Correlation-Id:
              $ref: './components.openapi.yaml#/components/headers/X-Grd-Correlation-Id'
            X-Grd-Trace-Id:
              $ref: './components.openapi.yaml#/components/headers/X-Grd-Trace-Id'
            X-RateLimit-Limit:
              $ref: './components.openapi.yaml#/components/headers/X-RateLimit-Limit'
            X-RateLimit-Remaining:
              $ref: './components.openapi.yaml#/components/headers/X-RateLimit-Remaining'
            X-RateLimit-Reset:
              $ref: './components.openapi.yaml#/components/headers/X-RateLimit-Reset'
          x-apidog-name: OK
        '400':
          $ref: './components.openapi.yaml#/components/responses/Error400'
        '401':
          $ref: './components.openapi.yaml#/components/responses/Error401'
        '403':
          $ref: './components.openapi.yaml#/components/responses/Error403'
        '404':
          $ref: './components.openapi.yaml#/components/responses/Error404'
        '409':
          $ref: './components.openapi.yaml#/components/responses/Error409'
        '422':
          $ref: './components.openapi.yaml#/components/responses/Error422'
        '429':
          $ref: './components.openapi.yaml#/components/responses/Error429'
        '500':
          $ref: './components.openapi.yaml#/components/responses/Error500'
      security: []
      x-apidog-folder: Ledger
      x-apidog-status: developing
      x-apidog-maintainer: Fernando Seguim
      x-run-in-apidog: https://app.apidog.com/web/project/719079/apis/api-11718081-run
    patch:
      summary: Atualize os dados de um ledger específico
      description: |
        :::warning
        Ao atualizar um metadata, quando o valor for `null`, caso a propriedade exista, ela será considerada para remoção, conforme a especificação do Json Merge Patch [RFC 7386](https://datatracker.ietf.org/doc/html/rfc7386).
        :::
      operationId: update_ledger
      tags:
        - Ledger
      parameters:
        - $ref: './components.openapi.yaml#/components/parameters/EntityId'
        - $ref: './components.openapi.yaml#/components/parameters/IdempotencyKey'
        - $ref: './components.openapi.yaml#/components/parameters/Accept'
        - $ref: './components.openapi.yaml#/components/parameters/AcceptLanguage'
        - $ref: './components.openapi.yaml#/components/parameters/ContentType'
        - $ref: './components.openapi.yaml#/components/parameters/CorrelationId'
      requestBody:
        required: true
        content:
          application/vnd.guardia.v1+json:
            schema:
              $ref: './components.openapi.yaml#/components/schemas/LedgerUpdateRequest'
      responses:
        '200':
          description: Ledger atualizado com sucesso.
          headers:
            Cache-Control:
              $ref: './components.openapi.yaml#/components/headers/Cache-Control'
            Content-Digest:
              $ref: './components.openapi.yaml#/components/headers/Content-Digest'
            Content-Language:
              $ref: './components.openapi.yaml#/components/headers/Content-Language'
            Content-Length:
              $ref: './components.openapi.yaml#/components/headers/Content-Length'
            Content-Type:
              $ref: './components.openapi.yaml#/components/headers/Content-Type'
            Idempotency-Key:
              $ref: './components.openapi.yaml#/components/headers/Idempotency-Key'
            Last-Modified:
              $ref: './components.openapi.yaml#/components/headers/Last-Modified'
            Strict-Transport-Security:
              $ref: './components.openapi.yaml#/components/headers/Strict-Transport-Security'
            X-Grd-Correlation-Id:
              $ref: './components.openapi.yaml#/components/headers/X-Grd-Correlation-Id'
            X-Grd-Trace-Id:
              $ref: './components.openapi.yaml#/components/headers/X-Grd-Trace-Id'
            X-RateLimit-Limit:
              $ref: './components.openapi.yaml#/components/headers/X-RateLimit-Limit'
            X-RateLimit-Remaining:
              $ref: './components.openapi.yaml#/components/headers/X-RateLimit-Remaining'
            X-RateLimit-Reset:
              $ref: './components.openapi.yaml#/components/headers/X-RateLimit-Reset'
          content:
            application/vnd.guardia.v1+json:
              schema:
                type: object
                properties:
                  data:
                    $ref: './components.openapi.yaml#/components/schemas/Ledger'
        '400':
          $ref: './components.openapi.yaml#/components/responses/Error400'
        '401':
          $ref: './components.openapi.yaml#/components/responses/Error401'
        '403':
          $ref: './components.openapi.yaml#/components/responses/Error403'
        '404':
          $ref: './components.openapi.yaml#/components/responses/Error404'
        '409':
          $ref: './components.openapi.yaml#/components/responses/Error409'
        '422':
          $ref: './components.openapi.yaml#/components/responses/Error422'
        '429':
          $ref: './components.openapi.yaml#/components/responses/Error429'
        '500':
          $ref: './components.openapi.yaml#/components/responses/Error500'
      security: []
      x-apidog-folder: Ledger
      x-apidog-status: developing
      x-apidog-maintainer: Fernando Seguim
      x-run-in-apidog: https://app.apidog.com/web/project/719079/apis/api-11718081-run
    delete:
      summary: Exclui um ledger específico
      deprecated: false
      description: |
        :::note
        Se o ledger possuir transações, a exclusão não será permitida.
        :::
      operationId: delete_ledger
      tags:
        - Ledger
      parameters:
        - $ref: './components.openapi.yaml#/components/parameters/EntityId'
        - $ref: './components.openapi.yaml#/components/parameters/Accept'
        - $ref: './components.openapi.yaml#/components/parameters/AcceptLanguage'
        - $ref: './components.openapi.yaml#/components/parameters/ContentType'
        - $ref: './components.openapi.yaml#/components/parameters/CorrelationId'
      responses:
        '204':
          description: Ledger excluído com sucesso.
          headers:
            Cache-Control:
              $ref: './components.openapi.yaml#/components/headers/Cache-Control'
            Content-Digest:
              $ref: './components.openapi.yaml#/components/headers/Content-Digest'
            Content-Language:
              $ref: './components.openapi.yaml#/components/headers/Content-Language'
            Content-Length:
              $ref: './components.openapi.yaml#/components/headers/Content-Length'
            Content-Type:
              $ref: './components.openapi.yaml#/components/headers/Content-Type'
            Last-Modified:
              $ref: './components.openapi.yaml#/components/headers/Last-Modified'
            Strict-Transport-Security:
              $ref: './components.openapi.yaml#/components/headers/Strict-Transport-Security'
            X-Grd-Correlation-Id:
              $ref: './components.openapi.yaml#/components/headers/X-Grd-Correlation-Id'
            X-Grd-Trace-Id:
              $ref: './components.openapi.yaml#/components/headers/X-Grd-Trace-Id'
            X-RateLimit-Limit:
              $ref: './components.openapi.yaml#/components/headers/X-RateLimit-Limit'
            X-RateLimit-Remaining:
              $ref: './components.openapi.yaml#/components/headers/X-RateLimit-Remaining'
            X-RateLimit-Reset:
              $ref: './components.openapi.yaml#/components/headers/X-RateLimit-Reset'
          x-apidog-name: No Content
        '400':
          $ref: './components.openapi.yaml#/components/responses/Error400'
        '401':
          $ref: './components.openapi.yaml#/components/responses/Error401'
        '403':
          $ref: './components.openapi.yaml#/components/responses/Error403'
        '404':
          $ref: './components.openapi.yaml#/components/responses/Error404'
        '409':
          $ref: './components.openapi.yaml#/components/responses/Error409'
        '422':
          $ref: './components.openapi.yaml#/components/responses/Error422'
        '429':
          $ref: './components.openapi.yaml#/components/responses/Error429'
        '500':
          $ref: './components.openapi.yaml#/components/responses/Error500'
      security: []
      x-apidog-folder: Ledger
      x-apidog-status: developing
      x-apidog-maintainer: Fernando Seguim
      x-run-in-apidog: https://app.apidog.com/web/project/719079/apis/api-11718082-run
  /v1/chapters:
    get:
      summary: Lista todos os chapters
      deprecated: false
      description: ''
      operationId: list_chapters
      tags:
        - Chapter
      parameters:
        - $ref: './components.openapi.yaml#/components/parameters/EntityIds'
        - $ref: './components.openapi.yaml#/components/parameters/ExternalEntityIds'
        - $ref: './components.openapi.yaml#/components/parameters/MetadataFilter'
        - $ref: './components.openapi.yaml#/components/parameters/IncludeDiscarded'
        - $ref: './components.openapi.yaml#/components/parameters/PageSize'
        - $ref: './components.openapi.yaml#/components/parameters/PageToken'
        - $ref: './components.openapi.yaml#/components/parameters/OrderBy'
        - $ref: './components.openapi.yaml#/components/parameters/Sort'
        - $ref: './components.openapi.yaml#/components/parameters/Accept'
        - $ref: './components.openapi.yaml#/components/parameters/AcceptLanguage'
        - $ref: './components.openapi.yaml#/components/parameters/ContentType'
        - $ref: './components.openapi.yaml#/components/parameters/CorrelationId'
      responses:
        '200':
          description: Lista de chapters.
          content:
            application/vnd.guardia.v1+json:
              schema:
                type: object
                properties:
                  data:
                    $ref: './components.openapi.yaml#/components/schemas/ListOfChapters'
                  pagination:
                    $ref: './components.openapi.yaml#/components/schemas/Pagination'
          headers:
            Cache-Control:
              $ref: './components.openapi.yaml#/components/headers/Cache-Control'
            Content-Language:
              $ref: './components.openapi.yaml#/components/headers/Content-Language'
            Content-Length:
              $ref: './components.openapi.yaml#/components/headers/Content-Length'
            Content-Type:
              $ref: './components.openapi.yaml#/components/headers/Content-Type'
            Strict-Transport-Security:
              $ref: './components.openapi.yaml#/components/headers/Strict-Transport-Security'
            X-Grd-Correlation-Id:
              $ref: './components.openapi.yaml#/components/headers/X-Grd-Correlation-Id'
            X-Grd-Trace-Id:
              $ref: './components.openapi.yaml#/components/headers/X-Grd-Trace-Id'
            X-RateLimit-Limit:
              $ref: './components.openapi.yaml#/components/headers/X-RateLimit-Limit'
            X-RateLimit-Remaining:
              $ref: './components.openapi.yaml#/components/headers/X-RateLimit-Remaining'
            X-RateLimit-Reset:
              $ref: './components.openapi.yaml#/components/headers/X-RateLimit-Reset'
        '400':
          $ref: './components.openapi.yaml#/components/responses/Error400'
        '401':
          $ref: './components.openapi.yaml#/components/responses/Error401'
        '403':
          $ref: './components.openapi.yaml#/components/responses/Error403'
        '429':
          $ref: './components.openapi.yaml#/components/responses/Error429'
        '500':
          $ref: './components.openapi.yaml#/components/responses/Error500'
        '409':
          $ref: './components.openapi.yaml#/components/responses/Error409'
        '422':
          $ref: './components.openapi.yaml#/components/responses/Error422'
      security: []
      x-apidog-folder: Chapter
      x-apidog-status: developing
      x-apidog-maintainer: Fernando Seguim
      x-run-in-apidog: https://app.apidog.com/web/project/719079/apis/api-11718083-run
    post:
      summary: Cria um novo chapter
      deprecated: false
      description: |
        Permite criar uma segmentação da ledger em ***Chapters*** (Capítulos),
        organizando transações e saldos por critérios específicos, como unidade
        de negócio ou centro de custo, para facilitar análises, relatórios e
        auditorias com maior precisão e flexibilidade.
      operationId: create_chapter
      tags:
        - Chapter
      parameters:
        - $ref: './components.openapi.yaml#/components/parameters/IdempotencyKey'
        - $ref: './components.openapi.yaml#/components/parameters/Accept'
        - $ref: './components.openapi.yaml#/components/parameters/AcceptLanguage'
        - $ref: './components.openapi.yaml#/components/parameters/ContentType'
        - $ref: './components.openapi.yaml#/components/parameters/CorrelationId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: './components.openapi.yaml#/components/schemas/ChapterCreateRequest'
            example:
              external_entity_id: fff78a0d3b5146a1ae80007e3d316714
              name: Investimentos
              description: Unidade de Negócio voltada para produtos de Investimentos.
              ledger_entity_id: f636cb1c46c4468e93c384a12530ee30
              metadata:
                foo: bar
      responses:
        '201':
          description: Chapter criado
          headers:
            Cache-Control:
              $ref: './components.openapi.yaml#/components/headers/Cache-Control'
            Content-Digest:
              $ref: './components.openapi.yaml#/components/headers/Content-Digest'
            Content-Language:
              $ref: './components.openapi.yaml#/components/headers/Content-Language'
            Content-Length:
              $ref: './components.openapi.yaml#/components/headers/Content-Length'
            Content-Type:
              $ref: './components.openapi.yaml#/components/headers/Content-Type'
            Idempotency-Key:
              $ref: './components.openapi.yaml#/components/headers/Idempotency-Key'
            Last-Modified:
              $ref: './components.openapi.yaml#/components/headers/Last-Modified'
            Strict-Transport-Security:
              $ref: './components.openapi.yaml#/components/headers/Strict-Transport-Security'
            X-Grd-Correlation-Id:
              $ref: './components.openapi.yaml#/components/headers/X-Grd-Correlation-Id'
            X-Grd-Trace-Id:
              $ref: './components.openapi.yaml#/components/headers/X-Grd-Trace-Id'
            X-RateLimit-Limit:
              $ref: './components.openapi.yaml#/components/headers/X-RateLimit-Limit'
            X-RateLimit-Remaining:
              $ref: './components.openapi.yaml#/components/headers/X-RateLimit-Remaining'
            X-RateLimit-Reset:
              $ref: './components.openapi.yaml#/components/headers/X-RateLimit-Reset'
          content:
            application/vnd.guardia.v1+json:
              schema:
                type: object
                properties:
                  data:
                    $ref: './components.openapi.yaml#/components/schemas/Chapter'
              example:
                data:
                  entity_id: '6683756247371778'
                  entity_type: CHAPTER
                  external_entity_id: fff78a0d3b5146a1ae80007e3d316714
                  version: 0
                  name: Investiments
                  description: Unidade de Negocio para produtos de Investimentos.
                  created_at: '2024-11-17T00:00:00.000Z'
                  updated_at: '2024-11-17T00:00:00.000Z'
                  discarded_at: null
                  metadata:
                    foo: bar
          x-apidog-name: Created
        '401':
          $ref: './components.openapi.yaml#/components/responses/Error401'
        '403':
          $ref: './components.openapi.yaml#/components/responses/Error403'
        '500':
          $ref: './components.openapi.yaml#/components/responses/Error500'
        '400':
          $ref: './components.openapi.yaml#/components/responses/Error400'
        '409':
          $ref: './components.openapi.yaml#/components/responses/Error409'
        '422':
          $ref: './components.openapi.yaml#/components/responses/Error422'
        '429':
          $ref: './components.openapi.yaml#/components/responses/Error429'
      security: []
      x-apidog-folder: Chapter
      x-apidog-status: developing
      x-apidog-maintainer: Fernando Seguim
      x-run-in-apidog: https://app.apidog.com/web/project/719079/apis/api-11718084-run
  /v1/chapters/{entity_id}:
    get:
      summary: Obtém um chapter específico
      deprecated: false
      description: ''
      operationId: get_chapter
      tags:
        - Chapter
      parameters:
        - $ref: './components.openapi.yaml#/components/parameters/EntityId'
        - $ref: './components.openapi.yaml#/components/parameters/Accept'
        - $ref: './components.openapi.yaml#/components/parameters/AcceptLanguage'
        - $ref: './components.openapi.yaml#/components/parameters/ContentType'
        - $ref: './components.openapi.yaml#/components/parameters/CorrelationId'
      responses:
        '200':
          description: Dados do chapter.
          content:
            application/vnd.guardia.v1+json:
              schema:
                type: object
                properties:
                  data:
                    $ref: './components.openapi.yaml#/components/schemas/Chapter'
          headers:
            Cache-Control:
              $ref: './components.openapi.yaml#/components/headers/Cache-Control'
            Content-Language:
              $ref: './components.openapi.yaml#/components/headers/Content-Language'
            Content-Length:
              $ref: './components.openapi.yaml#/components/headers/Content-Length'
            Content-Type:
              $ref: './components.openapi.yaml#/components/headers/Content-Type'
            Strict-Transport-Security:
              $ref: './components.openapi.yaml#/components/headers/Strict-Transport-Security'
            X-Grd-Correlation-Id:
              $ref: './components.openapi.yaml#/components/headers/X-Grd-Correlation-Id'
            X-Grd-Trace-Id:
              $ref: './components.openapi.yaml#/components/headers/X-Grd-Trace-Id'
            X-RateLimit-Limit:
              $ref: './components.openapi.yaml#/components/headers/X-RateLimit-Limit'
            X-RateLimit-Remaining:
              $ref: './components.openapi.yaml#/components/headers/X-RateLimit-Remaining'
            X-RateLimit-Reset:
              $ref: './components.openapi.yaml#/components/headers/X-RateLimit-Reset'
          x-apidog-name: OK
        '401':
          $ref: './components.openapi.yaml#/components/responses/Error401'
        '403':
          $ref: './components.openapi.yaml#/components/responses/Error403'
        '404':
          $ref: './components.openapi.yaml#/components/responses/Error404'
        '500':
          $ref: './components.openapi.yaml#/components/responses/Error500'
        '400':
          $ref: './components.openapi.yaml#/components/responses/Error400'
        '409':
          $ref: './components.openapi.yaml#/components/responses/Error409'
        '422':
          $ref: './components.openapi.yaml#/components/responses/Error422'
        '429':
          $ref: './components.openapi.yaml#/components/responses/Error429'
      security: []
      x-apidog-folder: Chapter
      x-apidog-status: developing
      x-apidog-maintainer: Fernando Seguim
      x-run-in-apidog: https://app.apidog.com/web/project/719079/apis/api-11718085-run
    patch:
      summary: Atualiza um chapter específico
      deprecated: false
      description: |
        > **Nota:**
        > Quando o valor for `null`, caso a propriedade exista, eleserá considerado para alteração.
      operationId: update_chapter
      tags:
        - Chapter
      parameters:
        - $ref: './components.openapi.yaml#/components/parameters/EntityId'
        - $ref: './components.openapi.yaml#/components/parameters/Accept'
        - $ref: './components.openapi.yaml#/components/parameters/AcceptLanguage'
        - $ref: './components.openapi.yaml#/components/parameters/ContentType'
        - $ref: './components.openapi.yaml#/components/parameters/IdempotencyKey'
        - $ref: './components.openapi.yaml#/components/parameters/CorrelationId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: './components.openapi.yaml#/components/schemas/ChapterUpdateRequest'
            example:
              external_entity_id: fff78a0d3b5146a1ae80007e3d316714
              name: Investimentos
              description: Unidade de Negócio voltada para produtos de Investimentos.
              ledger_entity_id: f636cb1c46c4468e93c384a12530ee30
              tags:
                - guardia
              metadata:
                foo: bar
      responses:
        '200':
          description: Chapter atualizado
          content:
            application/vnd.guardia.v1+json:
              schema:
                type: object
                properties:
                  data:
                    $ref: './components.openapi.yaml#/components/schemas/Chapter'
              example:
                data:
                  entity_id: '6683756247371778'
                  entity_type: CHAPTER
                  external_entity_id: fff78a0d3b5146a1ae80007e3d316714
                  version: 0
                  name: Receivables
                  description: Unidade de Negocio para produtos de Investimentos.
                  created_at: '2024-11-17T00:00:00.000Z'
                  updated_at: '2024-11-17T00:00:00.000Z'
                  discarded_at: null
                  metadata:
                    foo: bar
          headers:
            Cache-Control:
              $ref: './components.openapi.yaml#/components/headers/Cache-Control'
            Content-Digest:
              $ref: './components.openapi.yaml#/components/headers/Content-Digest'
            Content-Language:
              $ref: './components.openapi.yaml#/components/headers/Content-Language'
            Content-Length:
              $ref: './components.openapi.yaml#/components/headers/Content-Length'
            Content-Type:
              $ref: './components.openapi.yaml#/components/headers/Content-Type'
            Idempotency-Key:
              $ref: './components.openapi.yaml#/components/headers/Idempotency-Key'
            Last-Modified:
              $ref: './components.openapi.yaml#/components/headers/Last-Modified'
            Strict-Transport-Security:
              $ref: './components.openapi.yaml#/components/headers/Strict-Transport-Security'
            X-Grd-Correlation-Id:
              $ref: './components.openapi.yaml#/components/headers/X-Grd-Correlation-Id'
            X-Grd-Trace-Id:
              $ref: './components.openapi.yaml#/components/headers/X-Grd-Trace-Id'
            X-RateLimit-Limit:
              $ref: './components.openapi.yaml#/components/headers/X-RateLimit-Limit'
            X-RateLimit-Remaining:
              $ref: './components.openapi.yaml#/components/headers/X-RateLimit-Remaining'
            X-RateLimit-Reset:
              $ref: './components.openapi.yaml#/components/headers/X-RateLimit-Reset'
          x-apidog-name: OK
        '401':
          $ref: './components.openapi.yaml#/components/responses/Error401'
        '403':
          $ref: './components.openapi.yaml#/components/responses/Error403'
        '404':
          $ref: './components.openapi.yaml#/components/responses/Error404'
        '500':
          $ref: './components.openapi.yaml#/components/responses/Error500'
        '400':
          $ref: './components.openapi.yaml#/components/responses/Error400'
        '409':
          $ref: './components.openapi.yaml#/components/responses/Error409'
        '422':
          $ref: './components.openapi.yaml#/components/responses/Error422'
        '429':
          $ref: './components.openapi.yaml#/components/responses/Error429'
      security: []
      x-apidog-folder: Chapter
      x-apidog-status: developing
      x-apidog-maintainer: Fernando Seguim
      x-run-in-apidog: https://app.apidog.com/web/project/719079/apis/api-11718086-run
    delete:
      summary: Exclui um chapter específico
      deprecated: false
      description: |
        :::note
        Se o chapter possuir transações, a exclusão não será permitida.
        :::
      operationId: delete_chapter
      tags:
        - Chapter
      parameters:
        - $ref: './components.openapi.yaml#/components/parameters/EntityId'
        - $ref: './components.openapi.yaml#/components/parameters/Accept'
        - $ref: './components.openapi.yaml#/components/parameters/AcceptLanguage'
        - $ref: './components.openapi.yaml#/components/parameters/ContentType'
        - $ref: './components.openapi.yaml#/components/parameters/CorrelationId'
      responses:
        '204':
          description: Chapter excluído com sucesso
          headers:
            Cache-Control:
              $ref: './components.openapi.yaml#/components/headers/Cache-Control'
            Content-Digest:
              $ref: './components.openapi.yaml#/components/headers/Content-Digest'
            Content-Language:
              $ref: './components.openapi.yaml#/components/headers/Content-Language'
            Content-Length:
              $ref: './components.openapi.yaml#/components/headers/Content-Length'
            Content-Type:
              $ref: './components.openapi.yaml#/components/headers/Content-Type'
            Last-Modified:
              $ref: './components.openapi.yaml#/components/headers/Last-Modified'
            Strict-Transport-Security:
              $ref: './components.openapi.yaml#/components/headers/Strict-Transport-Security'
            X-Grd-Correlation-Id:
              $ref: './components.openapi.yaml#/components/headers/X-Grd-Correlation-Id'
            X-Grd-Trace-Id:
              $ref: './components.openapi.yaml#/components/headers/X-Grd-Trace-Id'
            X-RateLimit-Limit:
              $ref: './components.openapi.yaml#/components/headers/X-RateLimit-Limit'
            X-RateLimit-Remaining:
              $ref: './components.openapi.yaml#/components/headers/X-RateLimit-Remaining'
            X-RateLimit-Reset:
              $ref: './components.openapi.yaml#/components/headers/X-RateLimit-Reset'
          x-apidog-name: No Content
        '401':
          $ref: './components.openapi.yaml#/components/responses/Error401'
        '403':
          $ref: './components.openapi.yaml#/components/responses/Error403'
        '404':
          $ref: './components.openapi.yaml#/components/responses/Error404'
        '500':
          $ref: './components.openapi.yaml#/components/responses/Error500'
        '400':
          $ref: './components.openapi.yaml#/components/responses/Error400'
        '409':
          $ref: './components.openapi.yaml#/components/responses/Error409'
        '422':
          $ref: './components.openapi.yaml#/components/responses/Error422'
        '429':
          $ref: './components.openapi.yaml#/components/responses/Error429'
      security: []
      x-apidog-folder: Chapter
      x-apidog-status: developing
      x-apidog-maintainer: Fernando Seguim
      x-run-in-apidog: https://app.apidog.com/web/project/719079/apis/api-11718087-run
  /v1/assets:
    post:
      summary: Criar um novo asset
      deprecated: false
      description: |
        Um **asset** (ou ativo) é um recurso de valor econômico que pode ser
        possuído ou controlado por uma entidade, indivíduo ou instituição. No
        contexto financeiro, um ativo pode ser:


        - **Fiduciário**, quando seu valor é respaldado por um emissor de
        confiança, como moedas emitidas por governos ou títulos lastreados.

        - **Não fiduciário**, quando seu valor deriva de características
        intrínsecas ou da demanda do mercado. Entre esses ativos, podem estar
        commodities, criptomoedas e bens tangíveis, como um carro ou até mesmo
        contas (pedras historicamente utilizadas como meio de troca).


        Os **assets fiduciários**, baseados na **ISO 4712**, já estão
        disponíveis para uso no **Guardia**, mas você pode criar novos assets
        conforme sua necessidade. Os demais assets podem ser baseados em
        especificacoes como ISO 10962, MIC, ISIN ou um padrão interno da
        instituição.
      operationId: create_asset
      tags:
        - Asset
      parameters:
        - $ref: './components.openapi.yaml#/components/parameters/IdempotencyKey'
        - $ref: './components.openapi.yaml#/components/parameters/CorrelationId'
        - $ref: './components.openapi.yaml#/components/parameters/Accept'
        - $ref: './components.openapi.yaml#/components/parameters/AcceptLanguage'
        - $ref: './components.openapi.yaml#/components/parameters/ContentType'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                external_entity_id:
                  $ref: './components.openapi.yaml#/components/schemas/ExternalEntityID'
                code:
                  type: string
                number:
                  type: string
                exponent:
                  type: string
                is_fiat:
                  type: boolean
                locations:
                  type: array
                  items:
                    type: string
              required:
                - external_entity_id
                - code
                - number
                - exponent
                - is_fiat
                - locations
      responses:
        '201':
          description: Asset criado
          headers:
            Cache-Control:
              $ref: './components.openapi.yaml#/components/headers/Cache-Control'
            Content-Digest:
              $ref: './components.openapi.yaml#/components/headers/Content-Digest'
            Content-Language:
              $ref: './components.openapi.yaml#/components/headers/Content-Language'
            Content-Length:
              $ref: './components.openapi.yaml#/components/headers/Content-Length'
            Content-Type:
              $ref: './components.openapi.yaml#/components/headers/Content-Type'
            Idempotency-Key:
              $ref: './components.openapi.yaml#/components/headers/Idempotency-Key'
            Last-Modified:
              $ref: './components.openapi.yaml#/components/headers/Last-Modified'
            Strict-Transport-Security:
              $ref: './components.openapi.yaml#/components/headers/Strict-Transport-Security'
            X-Grd-Correlation-Id:
              $ref: './components.openapi.yaml#/components/headers/X-Grd-Correlation-Id'
            X-Grd-Trace-Id:
              $ref: './components.openapi.yaml#/components/headers/X-Grd-Trace-Id'
            X-RateLimit-Limit:
              $ref: './components.openapi.yaml#/components/headers/X-RateLimit-Limit'
            X-RateLimit-Remaining:
              $ref: './components.openapi.yaml#/components/headers/X-RateLimit-Remaining'
            X-RateLimit-Reset:
              $ref: './components.openapi.yaml#/components/headers/X-RateLimit-Reset'
          content:
            application/vnd.guardia.v1+json:
              schema:
                type: object
                properties:
                  data:
                    $ref: './components.openapi.yaml#/components/schemas/Asset'
              example:
                data:
                  entity_id: '6683756247371778'
                  entity_type: ASSET
                  external_entity_id: e9ad6a8ac4ce4a0b8e845c5d89e24322
                  version: 0
                  code: INT01
                  number: '2003202501'
                  exponent: 10
                  is_fiat: false
                  locations:
                    - NONE
                  created_at: '2024-11-17T00:00:00.000Z'
                  updated_at: '2024-11-17T00:00:00.000Z'
                  discarded_at: null
          x-apidog-name: Created
        '401':
          $ref: './components.openapi.yaml#/components/responses/Error401'
        '403':
          $ref: './components.openapi.yaml#/components/responses/Error403'
        '500':
          $ref: './components.openapi.yaml#/components/responses/Error500'
        '400':
          $ref: './components.openapi.yaml#/components/responses/Error400'
        '409':
          $ref: './components.openapi.yaml#/components/responses/Error409'
        '422':
          $ref: './components.openapi.yaml#/components/responses/Error422'
        '429':
          $ref: './components.openapi.yaml#/components/responses/Error429'
      security: []
      x-apidog-folder: Assets
      x-apidog-status: developing
      x-apidog-maintainer: Fernando Seguim
      x-run-in-apidog: https://app.apidog.com/web/project/719079/apis/api-14888485-run

components:
  headers:
    $ref: './components.openapi.yaml#/components/headers'
  schemas:
    $ref: './components.openapi.yaml#/components/schemas'
  responses:
    $ref: './components.openapi.yaml#/components/responses'

